### ISSUE TITLE
Add more information in the readme file

### ISSUE THREAD

**Issue by nathanshammah** [matt-lourens/hierarqcal#3]
Add information in the readme file at https://github.com/matt-lourens/dynamic-qcnn. 

Some stuff is standard and existing information that can be summarized in the Readme,  other stuff may need to be created. They include:
- introduction: scope of the package
- compatibility
- installation and requirements
- link to examples or documentation
- contribution guidelines information, code of conduct
- license
For more information have a look at https://github.com/unitaryfund/mitiq or https://github.com/qutip/qutip, for example. Some information are present in this guide https://github.com/nathanshammah/make-your-code-count.

Feel free to ping me, @stephendiadamo or Unitary Fund advisors for questions.

**Comment by stephendiadamo** [comment]
I'll add a pull request that adds some Sphinx documentation structure. Will help organize things like examples and further details.

**Comment by matt-lourens** [comment]
Hey guys, if you're happy with the following changes we can close the ticket. The documentation is [live](https://matt-lourens.github.io/hierarqcal/index.html) with tutorials for each framework. I've also updated the readme + added files for the standard info that @nathanshammah mentioned. The package is also published on pypi now: https://pypi.org/project/hierarqcal/
