### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by andresulea** [matt-lourens/hierarqcal#36]
Can I work on this project?

**Comment by matt-lourens** [comment]
Hi @andresulea, the two issues https://github.com/matt-lourens/hierarqcal/issues/27 and https://github.com/matt-lourens/hierarqcal/issues/28 are already resolved. But you're welcome to work on the others. I think https://github.com/matt-lourens/hierarqcal/issues/26 is close to being resolved but I'm not sure about the quantum chemistry issue
