### ISSUE TITLE
Add an example with short tutorial

### ISSUE THREAD

**Issue by nathanshammah** [matt-lourens/hierarqcal#5]
Adding an example with a tutorial on how to use the library. This could be in the form of a .ipynb notebook (or [myst](https://github.com/executablebooks/MyST-NB) file, i.e. more readable as a .md file but executable as a Jupyter notebook). This would definitely help the user to find out what the library can do.

This could be linked in the readme

**Comment by matt-lourens** [comment]
Done with #16
