### ISSUE TITLE
UnitaryHack Bounty - Research and Implement Sorting Networks with HierarQcal

### ISSUE THREAD

**Issue by matt-lourens** [matt-lourens/hierarqcal#50]
**Issue**: Research and implement sorting networks using the Python package **HierarQcal**.

## Overview
I recently came across the concept of [sorting networks](https://en.wikipedia.org/wiki/Sorting_network) and it seems like hierarQcal might be a good fit to implement (and hopefully generate/discover) these networks. I don't know much of the theory behind these sorting networks, so part of this task will be some research (but not neccesarily too much). The idea is to create a jupyter notebook tutorial containing demonstrations and some analysis of sorting networks implemented with hierarQcal. I've provided an example of bubble sort below, use that as reference for implementing two to three other sorting networks. Ultimately, the underlying reason for the issue is to explore how (or if) HierarQcal could facilitate efficient sorting algorithm discovery, contributing to automatic algorithm generation. Use this perspective during implementation and research of these algorithms.

### Outcome
- A Jupyter notebook tutorial that contains atleast two sorting networks (outside the bubble sort example, altough include it in the notebook).

### Example: Bubble Sort
Here's an example of a Bubble Sort implementation using HierarQcal:

```python
from hierarqcal import (
    Qcycle,
    Qmotif,
    Qinit,
    Qmask,
    Qunmask,
    Qpermute,
    Qpivot,
    plot_circuit,
    plot_motif,
    get_tensor_as_f,
    Qunitary,
    Qhierarchy,
)

def comparator(bits, symbols=None, state=None):
    v1, v2 = state[bits[0]], state[bits[1]]
    if v1 > v2:
        state[bits[0]], state[bits[1]] = v2, v1
    return state

h_comparator = Qunitary(comparator, n_symbols=0, arity=2)
array = [8, 5, 2, 1, 3, 4, 6, 7, 7, 7]
nb = len(array)  # number of indices
hierq = Qinit(len(array), state=array) + (
    Qcycle(stride=1, step=1, offset=0, mapping=h_comparator, boundary="open") + Qmask("*1")
) * (nb - 1)

# Plot the circuit
plot_circuit(hierq, plot_width=40)
sorted_array = hierq()
print(f"Starting array: {array}\n Sorted array: {sorted_array}")
```
![sorted](https://github.com/matt-lourens/hierarqcal/assets/51360109/06803348-245b-4843-8351-8121c6ab9e6f)

**Comment by AbdullahKazi500** [comment]
Bitonic sort works

**Comment by AbdullahKazi500** [comment]
@matt-lourens Please check and let me know

**Comment by AbdullahKazi500** [comment]
@matt-lourens bitonic py works

**Comment by Gopal-Dahale** [comment]
Hi @matt-lourens, I have made PR with some sorting networks (insertion, bubble and bitonic) along with explanations.

**Comment by AbdullahKazi500** [comment]
implemented bitonic in my first Two PRs and in the third PR I have implemented , cocktail and comb sort in the recent PR 
#56 @matt-lourens PLEASE review

**Comment by matt-lourens** [comment]
@Gopal-Dahale, @AbdullahKazi500 after reviewing your implementations I decided to go with @Gopal-Dahale solution for the bounty. It showcases core HierarQcal functionality in a pedagogical way, which was the main goal.

Thanks for both your efforts, it is very much appreciated :)

**Comment by AbdullahKazi500** [comment]
@matt-lourens No issues 
it was a good time working on this amazing project BTW
